CompileFlags:
  Add: [-Weverything, -Werror]

Diagnostics:
  ClangTidy:
    Add:
      [
        llvm-*,
        cert-*,
        clang-*,
        bugprone-*,
        performance-*,
        bugprone-*,
        portability-*,
        modernize-*,
      ]
    CheckOptions:
      WarnOnFloatingPointNarrowingConversion: false
    Remove: modernize-use-trailing-return-type
